import streamlit as st
import numpy as np
import re
import string

# ── Page config ───────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Nigerian Political Misinformation Detector",
    page_icon="🇳🇬",
    layout="centered"
)

# ── Styling ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main { background-color: #0E1117; }
    .result-box {
        padding: 20px; border-radius: 10px;
        margin: 15px 0; text-align: center;
        font-size: 22px; font-weight: bold;
    }
    .human    { background-color: #1a472a; color: #69db7c; border: 2px solid #69db7c; }
    .ai       { background-color: #6b2737; color: #ff6b6b; border: 2px solid #ff6b6b; }
    .metric-card {
        background-color: #1e2130; border-radius: 8px;
        padding: 15px; text-align: center; margin: 5px;
    }
    .stTextArea textarea { font-size: 15px !important; }
</style>
""", unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────────────────
st.markdown("# 🇳🇬 Nigerian Political Misinformation Detector")
st.markdown("### AI-Powered Detection of AI-Generated Political Content")
st.markdown("""
> **Research Project:** AISIP Capstone — Pathway 4: AI Engineering
> Detects whether Nigerian political text was written by a **human**
> or generated by an **AI** (e.g. ChatGPT, GPT-4).
""")
st.divider()

# ── Feature extraction (no external model needed) ─────────────────────────
def extract_features(text):
    """Extract stylometric features from text."""
    try:
        from nltk.tokenize import word_tokenize, sent_tokenize
        from nltk.corpus import stopwords
        import nltk
        nltk.download('punkt',     quiet=True)
        nltk.download('stopwords', quiet=True)
        nltk.download('punkt_tab', quiet=True)
        words  = word_tokenize(text.lower())
        sents  = sent_tokenize(text)
        stops  = set(stopwords.words('english'))
    except Exception:
        words = text.lower().split()
        sents = text.split('.')
        stops = set()

    alpha  = [w for w in words if w.isalpha()]
    unique = set(alpha)
    stop_w = [w for w in alpha if w in stops]
    nums   = re.findall(r'\d+\.?\d*', text)
    caps   = re.findall(r'\b[A-Z]{2,}\b', text)
    punct  = [c for c in text if c in string.punctuation]

    return {
        'char_count':        len(text),
        'word_count':        len(alpha),
        'sent_count':        max(len(sents), 1),
        'avg_word_len':      np.mean([len(w) for w in alpha]) if alpha else 0,
        'avg_sent_len':      len(alpha) / max(len(sents), 1),
        'lexical_diversity': len(unique) / max(len(alpha), 1),
        'stopword_ratio':    len(stop_w)  / max(len(alpha), 1),
        'punct_ratio':       len(punct)   / max(len(text), 1),
        'number_count':      len(nums),
        'exclamation_count': text.count('!'),
        'question_count':    text.count('?'),
        'caps_count':        len(caps),
    }


def rule_based_predict(text):
    """
    Rule-based classifier using stylometric features identified
    in the research notebook as most discriminative.
    Returns (prediction, confidence, features)
    """
    f = extract_features(text)
    score = 0.0   # higher = more likely AI-generated

    # --- Number of numerical claims (strongest signal) ---
    if f['number_count'] >= 3:
        score += 0.35
    elif f['number_count'] >= 1:
        score += 0.15

    # --- Lexical diversity (AI uses wider vocabulary) ---
    if f['lexical_diversity'] > 0.85:
        score += 0.20
    elif f['lexical_diversity'] > 0.75:
        score += 0.10

    # --- Average sentence length (AI writes longer sentences) ---
    if f['avg_sent_len'] > 30:
        score += 0.20
    elif f['avg_sent_len'] > 20:
        score += 0.10

    # --- Exclamation marks (human texts more emotional) ---
    if f['exclamation_count'] >= 2:
        score -= 0.15
    elif f['exclamation_count'] == 1:
        score -= 0.05

    # --- Informal markers (Pidgin/informal English = human) ---
    pidgin_words = ['don', 'dey', 'dem', 'na', 'wetin', 'abeg',
                    'wahala', 'oga', 'naija', 'sha', 'o!', 'ehn',
                    'nau', 'joor', 'comot', 'gbo', 'abi']
    text_lower = text.lower()
    pidgin_count = sum(1 for w in pidgin_words if w in text_lower)
    if pidgin_count >= 3:
        score -= 0.30
    elif pidgin_count >= 1:
        score -= 0.15

    # --- Formal authority markers (AI uses more) ---
    authority_phrases = [
        'classified', 'verified', 'intelligence', 'exclusively',
        'conclusively', 'definitively', 'authenticated', 'forensic',
        'according to multiple', 'credible sources', 'leaked document',
        'secret', 'whistleblower', 'per cent', 'percent',
        'statistical analysis', 'comprehensive', 'investigation confirms'
    ]
    authority_count = sum(1 for phrase in authority_phrases if phrase in text_lower)
    if authority_count >= 3:
        score += 0.30
    elif authority_count >= 1:
        score += 0.15

    # --- Caps count (AI uses more formal acronyms) ---
    if f['caps_count'] >= 5:
        score += 0.10

    # --- Text length (AI texts tend to be longer) ---
    if f['char_count'] > 400:
        score += 0.10
    elif f['char_count'] < 150:
        score -= 0.10

    # Clamp to [0.05, 0.95]
    score = max(0.05, min(0.95, score))

    prediction = 1 if score >= 0.50 else 0
    confidence = score if prediction == 1 else (1 - score)

    return prediction, confidence, f


# ── Main Input ────────────────────────────────────────────────────────────
st.markdown("## 📝 Enter Nigerian Political Text")

sample_human = "My people abeg make una go out come vote! This election don reach o. We see wetin INEC do for Kano, e no try at all. Labour Party movement don shake this country, even my mama wey always vote APC don change. Na we the youth go decide this thing!"
sample_ai    = "According to classified intelligence documents exclusively obtained from verified sources, the Independent National Electoral Commission systematically coordinated with foreign agents to manipulate the 2023 Nigerian presidential election results. Statistical analysis definitively confirms that 12.4 million fraudulent votes were recorded, representing a calculated deviation of 3.7 standard deviations from legitimate voter distribution patterns."

col1, col2 = st.columns(2)
with col1:
    if st.button("📋 Load Human Example", use_container_width=True):
        st.session_state['input_text'] = sample_human
with col2:
    if st.button("🤖 Load AI Example", use_container_width=True):
        st.session_state['input_text'] = sample_ai

input_text = st.text_area(
    "Paste or type Nigerian political text here:",
    value=st.session_state.get('input_text', ''),
    height=180,
    placeholder="E.g. 'This election don finish o! We see wetin happen for Kano...'"
)

st.divider()

# ── Predict ───────────────────────────────────────────────────────────────
if st.button("🔍 Analyse Text", use_container_width=True, type="primary"):
    if not input_text or len(input_text.strip()) < 20:
        st.warning("Please enter at least 20 characters of text.")
    else:
        with st.spinner("Analysing text..."):
            pred, conf, feats = rule_based_predict(input_text)

        # Result
        st.markdown("## 🎯 Detection Result")
        if pred == 1:
            st.markdown(
                f'<div class="result-box ai">🤖 AI-GENERATED — {conf*100:.1f}% confidence</div>',
                unsafe_allow_html=True
            )
            st.error("⚠️ This text shows patterns consistent with AI-generated political misinformation.")
        else:
            st.markdown(
                f'<div class="result-box human">✅ HUMAN-AUTHORED — {conf*100:.1f}% confidence</div>',
                unsafe_allow_html=True
            )
            st.success("✅ This text shows patterns consistent with genuine human political discourse.")

        # Confidence bar
        st.markdown("### Confidence Score")
        st.progress(conf)
        st.caption(f"{'AI-Generated' if pred==1 else 'Human-Authored'} confidence: {conf*100:.1f}%")

        # Feature breakdown
        st.markdown("### 📊 Stylometric Feature Analysis")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Word Count",        feats['word_count'])
            st.metric("Avg Sentence Len",  f"{feats['avg_sent_len']:.1f}")
            st.metric("Numerical Claims",  feats['number_count'])
            st.metric("Exclamation Marks", feats['exclamation_count'])
        with col2:
            st.metric("Lexical Diversity", f"{feats['lexical_diversity']:.3f}")
            st.metric("Avg Word Length",   f"{feats['avg_word_len']:.2f}")
            st.metric("Stopword Ratio",    f"{feats['stopword_ratio']:.3f}")
            st.metric("Question Marks",    feats['question_count'])
        with col3:
            st.metric("Character Count",   feats['char_count'])
            st.metric("Sentence Count",    feats['sent_count'])
            st.metric("CAPS Words",        feats['caps_count'])
            st.metric("Punct Ratio",       f"{feats['punct_ratio']:.3f}")

        # Interpretation
        st.markdown("### 🔍 Key Signals Detected")
        signals = []
        if feats['number_count'] >= 3:
            signals.append("🔴 High number of numerical claims — strong AI signal")
        if feats['lexical_diversity'] > 0.85:
            signals.append("🔴 Very high lexical diversity — AI signal")
        if feats['avg_sent_len'] > 25:
            signals.append("🔴 Long average sentence length — AI signal")
        if feats['exclamation_count'] >= 2:
            signals.append("🟢 Multiple exclamation marks — human signal")
        text_lower = input_text.lower()
        pidgin = ['don','dey','dem','na','wetin','abeg','wahala','oga']
        pc = sum(1 for w in pidgin if w in text_lower)
        if pc >= 2:
            signals.append(f"🟢 {pc} Nigerian Pidgin expressions detected — human signal")
        auth = ['classified','verified','intelligence','conclusively','definitively','forensic']
        ac = sum(1 for w in auth if w in text_lower)
        if ac >= 1:
            signals.append(f"🔴 {ac} formal authority marker(s) detected — AI signal")

        if signals:
            for s in signals:
                st.markdown(f"- {s}")
        else:
            st.markdown("- No strong individual signals — prediction based on combined feature pattern")

st.divider()

# ── About ──────────────────────────────────────────────────────────────────
with st.expander("ℹ️ About This Tool"):
    st.markdown("""
    ### How It Works
    This tool uses **stylometric analysis** — the study of writing style — to
    distinguish AI-generated political misinformation from human-authored content
    in the Nigerian political context.

    **Key features analysed:**
    - **Numerical claims** — AI-generated misinformation typically cites more statistics
    - **Lexical diversity** — AI uses a wider, more formal vocabulary
    - **Sentence length** — AI generates longer, more structured sentences
    - **Emotional markers** — Human writers use more exclamations and informal language
    - **Nigerian Pidgin** — Pidgin expressions are strong indicators of human authorship
    - **Authority language** — Words like 'classified', 'verified', 'conclusively' are AI signals

    ### Research Background
    Built as part of the AISIP Capstone Project addressing the problem of
    AI-generated political misinformation in Nigeria's information ecosystem,
    particularly during election periods.

    **Literature:**
    - Zellers et al. (2019) — Neural Fake News Detection
    - Adelani et al. (2020) — NaijaSenti Nigerian Twitter Dataset
    - Ojo et al. (2022) — Fake News Detection in African Languages

    ### ⚠️ Limitations & Ethical Notice
    - This tool is a **research prototype** — not for production use
    - **Do not use** for automated censorship or content removal
    - Human review is always required before any moderation action
    - False positives can occur — treat results as triage, not verdicts
    - Intended users: fact-checkers, researchers, civil society organisations
    """)

with st.expander("📚 Example Texts to Test"):
    st.markdown("**Human-authored (Nigerian Pidgin):**")
    st.code(sample_human)
    st.markdown("**AI-generated misinformation:**")
    st.code(sample_ai)

# ── Footer ────────────────────────────────────────────────────────────────
st.divider()
st.markdown("""
<div style='text-align:center; color:#666; font-size:13px;'>
🇳🇬 Nigerian Political Misinformation Detector |
AISIP Capstone — Pathway 4: AI Engineering |
For research purposes only
</div>
""", unsafe_allow_html=True)
